apiVersion: v1
kind: Service
metadata:
  labels:
    app: simple-nodejs-app
  name: simple-nodejs-app
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: simple-nodejs-app
